name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Save pnpm deps JSON
        run: pnpm ls --json --long > pnpm-deps.json

      - name: Check for deprecated packages
        run: node ./scripts/check-deprecated.js pnpm-deps.json

      - name: Run tests
        run: pnpm test
